# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-25 20:23
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.BooleanField(default=False)),
                ('attended', models.BooleanField(default=False)),
                ('count', models.IntegerField(default=0)),
                ('passed_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MainEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('content', ckeditor.fields.RichTextField()),
                ('appcontent', models.TextField(default='', max_length=3000)),
                ('short_description', models.CharField(blank=True, max_length=140)),
                ('rules', models.CharField(blank=True, max_length=200)),
                ('detail_rules', models.TextField(blank=True, default='', max_length=300, null=True)),
                ('is_kernel', models.BooleanField(default=False)),
                ('icon', models.ImageField(blank=True, upload_to='icons')),
                ('date', models.CharField(default='TBA', max_length=100)),
                ('time', models.CharField(default='TBA', max_length=100)),
                ('venue', models.CharField(default='TBA', max_length=100)),
                ('min_team_size', models.IntegerField(default=0)),
                ('max_team_size', models.IntegerField(default=0)),
                ('min_teams', models.IntegerField(default=0)),
                ('max_teams', models.IntegerField(default=0)),
                ('contact', models.CharField(default='', max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='MainParticipation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pcr_approved', models.BooleanField(default=False)),
                ('cr_approved', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.MainEvent')),
            ],
        ),
        migrations.CreateModel(
            name='MainProfShow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('appcontent', models.TextField(default='', max_length=3000)),
                ('short_description', models.CharField(blank=True, max_length=140)),
                ('date', models.CharField(default='TBA', max_length=100)),
                ('time', models.CharField(default='TBA', max_length=100)),
                ('venue', models.CharField(default='TBA', max_length=100)),
                ('contact', models.CharField(default='', max_length=140)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
    ]
