# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-18 12:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20180518_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='introevent',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventmodel', to=settings.AUTH_USER_MODEL),
        ),
    ]
