# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-20 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20180518_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='introevent',
            name='trivial_field',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
