# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-20 10:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0007_auto_20180520_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='introevent',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventmodel', to=settings.AUTH_USER_MODEL),
        ),
    ]
