# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-14 17:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20181014_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainprofshow',
            name='organization',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shows', to='events.Organization'),
        ),
    ]
