# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-15 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20181014_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainevent',
            name='duration',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
