# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-16 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20181014_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainevent',
            name='detail_rules',
            field=models.TextField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
