# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-24 13:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auto_20181024_1755'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainprofshow',
            old_name='organization',
            new_name='organizations',
        ),
    ]
