# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-19 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordwars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_no',
            field=models.IntegerField(default=1),
        ),
    ]
