# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-16 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GenParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('phone', models.CharField(default='', max_length=13)),
                ('gender', models.CharField(max_length=6)),
                ('email_address', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Roctaves',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('genre', models.CharField(default='', max_length=50)),
                ('email_address', models.EmailField(max_length=254)),
                ('phone', models.CharField(default='', max_length=13)),
                ('number_of_participants', models.IntegerField(default=1)),
                ('elimination_preference', models.CharField(max_length=25)),
                ('entry1', models.CharField(max_length=100)),
                ('entry2', models.CharField(max_length=100)),
                ('enteries', models.TextField(max_length=200, null=True)),
            ],
        ),
    ]
