# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-23 14:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regsoft', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('uniqueid', models.CharField(blank=True, max_length=10, null=True)),
                ('cord', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DC_Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(blank=True, max_length=500, null=True)),
                ('blankets', models.IntegerField(blank=True, default=0, null=True)),
                ('mattress', models.IntegerField(blank=True, default=0, null=True)),
                ('tents', models.IntegerField(blank=True, default=0, null=True)),
                ('pillows', models.IntegerField(blank=True, default=0, null=True)),
                ('spikes', models.IntegerField(blank=True, default=0, null=True)),
                ('bedsheets', models.IntegerField(blank=True, default=0, null=True)),
                ('quilts', models.IntegerField(blank=True, default=0, null=True)),
                ('buckets', models.IntegerField(blank=True, default=0, null=True)),
                ('mugs', models.IntegerField(blank=True, default=0, null=True)),
                ('fans', models.IntegerField(blank=True, default=0, null=True)),
                ('tables', models.IntegerField(blank=True, default=0, null=True)),
                ('table_cloths', models.IntegerField(blank=True, default=0, null=True)),
                ('chairs', models.IntegerField(blank=True, default=0, null=True)),
                ('red_carpets', models.IntegerField(blank=True, default=0, null=True)),
                ('green_carpets', models.IntegerField(blank=True, default=0, null=True)),
                ('curtains', models.IntegerField(blank=True, default=0, null=True)),
                ('halogen_lamps', models.IntegerField(blank=True, default=0, null=True)),
                ('sodium_lamps', models.IntegerField(blank=True, default=0, null=True)),
                ('item1', models.IntegerField(blank=True, default=0, null=True)),
                ('item2', models.IntegerField(blank=True, default=0, null=True)),
                ('item3', models.IntegerField(blank=True, default=0, null=True)),
                ('item4', models.IntegerField(blank=True, default=0, null=True)),
                ('item5', models.IntegerField(blank=True, default=0, null=True)),
                ('dc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regsoft.DC')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(blank=True, max_length=500, null=True)),
                ('blankets', models.IntegerField(blank=True, default=0, null=True)),
                ('mattress', models.IntegerField(blank=True, default=0, null=True)),
                ('pillows', models.IntegerField(blank=True, default=0, null=True)),
                ('spikes', models.IntegerField(blank=True, default=0, null=True)),
                ('bedsheets', models.IntegerField(blank=True, default=0, null=True)),
                ('quilts', models.IntegerField(blank=True, default=0, null=True)),
                ('buckets', models.IntegerField(blank=True, default=0, null=True)),
                ('mugs', models.IntegerField(blank=True, default=0, null=True)),
                ('fans', models.IntegerField(blank=True, default=0, null=True)),
                ('bulbs', models.IntegerField(blank=True, default=0, null=True)),
                ('water_campers', models.IntegerField(blank=True, default=0, null=True)),
                ('water_drums', models.IntegerField(blank=True, default=0, null=True)),
                ('waste_drums', models.IntegerField(blank=True, default=0, null=True)),
                ('tables', models.IntegerField(blank=True, default=0, null=True)),
                ('table_cloth', models.IntegerField(blank=True, default=0, null=True)),
                ('chairs', models.IntegerField(blank=True, default=0, null=True)),
                ('red_carpets', models.IntegerField(blank=True, default=0, null=True)),
                ('green_carpets', models.IntegerField(blank=True, default=0, null=True)),
                ('curtains', models.IntegerField(blank=True, default=0, null=True)),
                ('halogen_lamps', models.IntegerField(blank=True, default=0, null=True)),
                ('sodium_lamps', models.IntegerField(blank=True, default=0, null=True)),
                ('tents', models.IntegerField(blank=True, default=0, null=True)),
                ('iron_poles', models.IntegerField(blank=True, default=0, null=True)),
                ('paper_rolls', models.IntegerField(blank=True, default=0, null=True)),
                ('bamboo_poles', models.IntegerField(blank=True, default=0, null=True)),
                ('ropes', models.IntegerField(blank=True, default=0, null=True)),
                ('wires', models.IntegerField(blank=True, default=0, null=True)),
                ('item1', models.IntegerField(blank=True, default=0, null=True)),
                ('item2', models.IntegerField(blank=True, default=0, null=True)),
                ('item3', models.IntegerField(blank=True, default=0, null=True)),
                ('item4', models.IntegerField(blank=True, default=0, null=True)),
                ('item5', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('tender', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='inventory',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regsoft.Location'),
        ),
    ]
