# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-25 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regsoft', '0003_auto_20181024_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='dc_inventory',
            name='bamboo_poles',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='dc_inventory',
            name='bulbs',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='dc_inventory',
            name='iron_poles',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='dc_inventory',
            name='paper_rolls',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='dc_inventory',
            name='ropes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='dc_inventory',
            name='waste_drums',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='dc_inventory',
            name='water_campers',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='dc_inventory',
            name='water_drums',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='dc_inventory',
            name='wires',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
