# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-05 06:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GenParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('phone', models.CharField(default='', max_length=13)),
                ('gender', models.CharField(blank=True, default='', max_length=6, null=True)),
                ('email_address', models.EmailField(default='', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='PurpleProseExtension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.CharField(default='', max_length=100)),
                ('year_and_stream_of_study', models.CharField(default='', max_length=100)),
                ('city_of_participation', models.CharField(default='', max_length=30)),
                ('entry', models.TextField(max_length=300)),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='preregistration.GenParticipant')),
            ],
        ),
        migrations.CreateModel(
            name='RapWarsExtension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rapper_name', models.CharField(default='', max_length=100)),
                ('city_of_participation', models.CharField(default='', max_length=30)),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='preregistration.GenParticipant')),
            ],
        ),
        migrations.CreateModel(
            name='Roctaves',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('genre', models.CharField(default='', max_length=50)),
                ('email_address', models.EmailField(max_length=254)),
                ('phone', models.CharField(default='', max_length=13)),
                ('number_of_participants', models.IntegerField(default=1)),
                ('elimination_preference', models.CharField(max_length=25)),
                ('entry1', models.CharField(max_length=100)),
                ('entry2', models.CharField(max_length=100)),
                ('enteries', models.TextField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StandupSoapboxExtension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_doing_standup', models.CharField(default='', max_length=20)),
                ('previous_competition', models.TextField(default='', max_length=300)),
                ('city_of_participation', models.CharField(default='', max_length=30)),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='preregistration.GenParticipant')),
            ],
        ),
    ]
