# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-21 02:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roctaves',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('genre', models.CharField(default='', max_length=50)),
                ('email_address', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(default='', max_length=13)),
                ('number_of_participants', models.IntegerField(default=1)),
                ('eliminationpreference', models.CharField(choices=[('1', 'Bangalore'), ('2', 'Mumbai'), ('3', 'Delhi'), ('4', 'Kolkata'), ('5', 'Guwahati'), ('6', 'Kochi'), ('7', 'Chennai'), ('8', 'Kathmandu')], max_length=25)),
                ('entry1', models.CharField(max_length=100)),
                ('entry2', models.CharField(max_length=100)),
            ],
        ),
    ]
