# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-18 23:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roctaves',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('phone', models.CharField(default='', max_length=13)),
                ('gender', models.CharField(max_length=6)),
                ('email_address', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
