# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-24 16:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preregistration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoetrySlamExtension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='preregistration.GenParticipant')),
            ],
        ),
        migrations.CreateModel(
            name='RapWarsExtension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rapper_name', models.CharField(default='', max_length=100)),
                ('city_of_participation', models.CharField(default='', max_length=30)),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='preregistration.GenParticipant')),
            ],
        ),
        migrations.RemoveField(
            model_name='poetryslam',
            name='poetryslam_participant',
        ),
        migrations.RemoveField(
            model_name='rapwars',
            name='RapWars_participant',
        ),
        migrations.DeleteModel(
            name='PoetrySlam',
        ),
        migrations.DeleteModel(
            name='RapWars',
        ),
    ]
