# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-21 04:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preregistration', '0002_auto_20180421_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roctaves',
            name='elimination_preference',
            field=models.CharField(choices=[('Bangalore', 'Bangalore'), ('Mumbai', 'Mumbai'), ('Delhi', 'Delhi'), ('Kolkata', 'Kolkata'), ('Guwahati', 'Guwahati'), ('Kochi', 'Kochi'), ('Chennai', 'Chennai'), ('Kathmandu', 'Kathmandu')], max_length=25),
        ),
        migrations.AlterField(
            model_name='roctaves',
            name='email_address',
            field=models.EmailField(max_length=254),
        ),
    ]
