# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-30 10:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preregistration', '0003_auto_20180525_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurpleProseExtension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yearandstreamofstudy', models.CharField(default='', max_length=100)),
                ('entry', models.CharField(max_length=100, null='')),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='preregistration.GenParticipant')),
            ],
        ),
    ]
