# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-30 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preregistration', '0004_purpleproseextension'),
    ]

    operations = [
        migrations.AddField(
            model_name='purpleproseextension',
            name='city_of_participation',
            field=models.CharField(default='', max_length=30),
        ),
    ]
