# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-30 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preregistration', '0005_purpleproseextension_city_of_participation'),
    ]

    operations = [
        migrations.AddField(
            model_name='purpleproseextension',
            name='college',
            field=models.CharField(default='', max_length=100),
        ),
    ]
