# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-30 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preregistration', '0006_purpleproseextension_college'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genparticipant',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
