# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-30 16:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preregistration', '0009_auto_20180530_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandupSoapboxExtension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_doing_standup', models.CharField(default='', max_length=20)),
                ('previous_competition', models.TextField(default='', max_length=300)),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='preregistration.GenParticipant')),
            ],
        ),
    ]
