# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-30 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preregistration', '0010_standupsoapboxextension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genparticipant',
            name='city',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='genparticipant',
            name='gender',
            field=models.CharField(default='', max_length=6, null=True),
        ),
    ]
