# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-31 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preregistration', '0012_auto_20180531_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='standupsoapboxextension',
            name='city_of_participation',
            field=models.CharField(default='', max_length=30),
        ),
    ]
