# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-03 07:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preregistration', '0013_standupsoapboxextension_city_of_participation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poetryslamextension',
            name='participant',
        ),
        migrations.DeleteModel(
            name='PoetrySlamExtension',
        ),
    ]
