# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-26 03:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preregistration', '0015_auto_20180723_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purpleproseextension',
            name='entry',
            field=models.TextField(max_length=300),
        ),
    ]
