# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-04 10:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preregistration', '0016_auto_20180726_0903'),
        ('preregistration', '0016_auto_20180730_1805'),
    ]

    operations = [
    ]
