# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-03 09:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('swd', models.PositiveIntegerField(default=0)),
                ('cash', models.PositiveIntegerField(default=0)),
                ('instamojo', models.PositiveIntegerField(default=0)),
                ('transfers', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ItemClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20)),
                ('price', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True, default='')),
                ('is_combo', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=True)),
                ('stock', models.PositiveIntegerField(default=500)),
                ('is_veg', models.BooleanField(default=False)),
                ('size', models.CharField(max_length=10, null=True)),
                ('colors', models.CharField(max_length=10, null=True)),
                ('TYPE', models.CharField(max_length=20, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ItemInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('confirmed', models.BooleanField(default=False)),
                ('cancelled', models.BooleanField(default=False)),
                ('paid', models.BooleanField(default=False)),
                ('received', models.BooleanField(default=False)),
                ('itemclass', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instances', to='shop.ItemClass')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='OrderFragment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Stall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=0)),
                ('transfer_type', models.CharField(choices=[('buy', 'buy'), ('add', 'add'), ('recieve', 'recieve'), ('transfer', 'transfer')], default='buy', max_length=10, null=True)),
                ('refund_id', models.CharField(default='', max_length=30)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('phone', models.BigIntegerField(default=0)),
                ('balance', models.PositiveIntegerField(default=0)),
                ('profile', models.CharField(choices=[('bitsian', 'bitsian'), ('participant', 'participant'), ('stall', 'stall')], max_length=16)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='transfer_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfered_out', to='shop.Wallet'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transfer_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfered_in', to='shop.Wallet'),
        ),
        migrations.AddField(
            model_name='orderfragment',
            name='stall',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='shop.Stall'),
        ),
        migrations.AddField(
            model_name='orderfragment',
            name='transaction',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.Transaction'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='shop.Wallet'),
        ),
        migrations.AddField(
            model_name='iteminstance',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='shop.OrderFragment'),
        ),
        migrations.AddField(
            model_name='itemclass',
            name='stall',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu', to='shop.Stall'),
        ),
    ]
