# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-05 09:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_orderfragment_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemclass',
            old_name='colors',
            new_name='color',
        ),
        migrations.RenameField(
            model_name='itemclass',
            old_name='TYPE',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='iteminstance',
            name='cancelled',
        ),
        migrations.RemoveField(
            model_name='iteminstance',
            name='confirmed',
        ),
        migrations.RemoveField(
            model_name='iteminstance',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='iteminstance',
            name='received',
        ),
        migrations.AddField(
            model_name='orderfragment',
            name='status',
            field=models.CharField(choices=[('in-review', 'in-review'), ('accepted', 'accepted'), ('declined', 'declined'), ('finished', 'finished'), ('completed', 'completed'), ('cancelled', 'cancelled')], default='in-review', max_length=20),
        ),
        migrations.AlterField(
            model_name='itemclass',
            name='stall',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu', to='shop.Stall'),
        ),
        migrations.AlterField(
            model_name='iteminstance',
            name='itemclass',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='shop.ItemClass'),
        ),
        migrations.AlterField(
            model_name='iteminstance',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.OrderFragment'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='shop.Wallet'),
        ),
        migrations.AlterField(
            model_name='orderfragment',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fragments', to='shop.Order'),
        ),
        migrations.AlterField(
            model_name='orderfragment',
            name='stall',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='shop.Stall'),
        ),
        migrations.AlterField(
            model_name='orderfragment',
            name='transaction',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Transaction'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shop.Balance'),
        ),
    ]
