# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-16 09:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20180906_2010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemclass',
            old_name='type',
            new_name='itemtype',
        ),
        migrations.AlterField(
            model_name='stall',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stall', to=settings.AUTH_USER_MODEL),
        ),
    ]
