# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-09 10:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20180906_2010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemclass',
            old_name='type',
            new_name='item_type',
        ),
    ]
