# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-16 11:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20180916_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='stall',
            name='phone',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orderfragment',
            name='status',
            field=models.CharField(choices=[('received', 'received'), ('declined', 'declined'), ('finished', 'finished')], default='in-review', max_length=20),
        ),
        migrations.AlterField(
            model_name='stall',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transfer_type',
            field=models.CharField(choices=[('buy', 'buy'), ('add', 'add'), ('transfer', 'transfer')], default='buy', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='profile',
            field=models.CharField(choices=[('B', 'bitsian'), ('P', 'participant'), ('S', 'stall')], max_length=1),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet', to=settings.AUTH_USER_MODEL),
        ),
    ]
