# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-20 10:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20180919_2051'),
        ('shop', '0007_auto_20180919_2224'),
    ]

    operations = [
    ]
