# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-22 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_merge_20180920_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderfragment',
            name='status',
            field=models.CharField(choices=[('P', 'pending'), ('A', 'accepted'), ('D', 'declined'), ('F', 'finished')], default='P', max_length=1),
        ),
    ]
