# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-23 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20180922_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderfragment',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Accepted'), ('D', 'Declined'), ('F', 'Finished')], default='P', max_length=1),
        ),
    ]
