# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-23 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20180923_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemclass',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='stall',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
