# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-24 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20180923_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='query_string',
            field=models.TextField(blank=True, null=True),
        ),
    ]
