# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-25 04:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20180918_2110'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0012_order_query_string'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.SmallIntegerField(blank=True, default=0)),
                ('prof_show', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.MainProfShow')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
