# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-30 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20180930_0244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='refund_id',
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_id',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
    ]
