# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-18 18:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_auto_20181014_2307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='query_string',
        ),
    ]
