# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-21 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_remove_order_query_string'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderfragment',
            name='otp',
            field=models.PositiveIntegerField(default=1234),
        ),
        migrations.AlterField(
            model_name='orderfragment',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Accepted'), ('D', 'Declined'), ('R', 'Ready'), ('F', 'Finished')], default='P', max_length=1),
        ),
    ]
