# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-21 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_auto_20181022_0157'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderfragment',
            name='show_otp',
            field=models.BooleanField(default=False),
        ),
    ]
