# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-23 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_auto_20181023_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='registration_token',
            field=models.CharField(default='', max_length=500),
        ),
    ]
