# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-24 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_wallet_registration_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebugInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity', models.CharField(choices=[('A', 'Android'), ('I', 'IOS'), ('W', 'Web'), ('S', 'Server')], max_length=1)),
                ('debug_info', models.CharField(max_length=10000)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
