# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-25 19:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_tickets_consumed'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('tickets', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.Tickets')),
            ],
        ),
    ]
