# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-26 05:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_tickettransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettransaction',
            name='num',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
