# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-26 07:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_tickettransaction_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickettransaction',
            name='tickets',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickettransaction', to='shop.Tickets'),
        ),
    ]
