# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-27 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_auto_20181027_0356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='registration_token',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
    ]
