# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-27 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0033_auto_20181027_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='is_excel_sheet',
            field=models.BooleanField(default=False),
        ),
    ]
