# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-29 00:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0034_tickets_is_excel_sheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='qr_no',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
