# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-25 20:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import registrations.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_mainattendance_mainevent_mainparticipation_mainprofshow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bitsian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_id', models.CharField(blank=True, max_length=20, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(blank=True, max_length=1, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('barcode', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('phone', models.BigIntegerField(default=0, null=True)),
                ('bhawan', models.CharField(blank=True, max_length=20, null=True)),
                ('room_no', models.IntegerField(default=0)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CheckoutGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_retained', models.IntegerField(default=0)),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('group_code', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmailGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_deduct', models.IntegerField(default=0)),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('group_code', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('barcode', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('state', models.CharField(max_length=50)),
                ('phone', models.BigIntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
                ('year_of_study', models.CharField(max_length=3, null=True)),
                ('head_of_society', models.BooleanField(default=False)),
                ('profile_pic', models.ImageField(null=True, upload_to=registrations.models.user_directory_path)),
                ('verify_docs', models.ImageField(default=None, null=True, upload_to=registrations.models.user_directory_path)),
                ('email_verified', models.BooleanField(default=False)),
                ('email_token', models.CharField(blank=True, max_length=32, null=True)),
                ('is_cr', models.BooleanField(default=False)),
                ('pcr_approved', models.BooleanField(default=False)),
                ('paid', models.BooleanField(default=False)),
                ('pcr_final', models.BooleanField(default=False)),
                ('firewallz_passed', models.BooleanField(default=False)),
                ('acco', models.BooleanField(default=False)),
                ('controlz', models.BooleanField(default=False, verbose_name='controlz passed')),
                ('controlz_paid', models.BooleanField(default=False)),
                ('curr_paid', models.BooleanField(default=False)),
                ('curr_controlz_paid', models.BooleanField(default=False)),
                ('recnacc_time', models.DateTimeField(null=True)),
                ('is_g_leader', models.BooleanField(default=False)),
                ('cr_approved', models.BooleanField(default=False)),
                ('ems_code', models.CharField(default='', max_length=10, null=True)),
                ('is_guest', models.BooleanField(default=False)),
                ('bits_id', models.CharField(blank=True, max_length=20, null=True)),
                ('checkout_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registrations.CheckoutGroup')),
                ('college', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='registrations.College')),
                ('email_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registrations.EmailGroup')),
                ('events', models.ManyToManyField(through='events.MainParticipation', to='events.MainEvent')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registrations.Group')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.IntegerField(default=0)),
                ('created_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='participant',
            name='payment_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registrations.PaymentGroup'),
        ),
        migrations.AddField(
            model_name='participant',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
