# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-19 15:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import registrations.models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0002_auto_20180826_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='barcode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='checkout_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registrations.CheckoutGroup'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='email_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registrations.EmailGroup'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='ems_code',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='events',
            field=models.ManyToManyField(blank=True, through='events.MainParticipation', to='events.MainEvent'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registrations.Group'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='payment_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registrations.PaymentGroup'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=registrations.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='participant',
            name='recnacc_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='state',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='participant',
            name='verify_docs',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=registrations.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='participant',
            name='year_of_study',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
