# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-05 14:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0003_remove_participant_ems_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='verify_docs',
        ),
    ]
