# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-22 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0005_auto_20180917_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitsian',
            name='barcode',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='barcode',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
