# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-22 13:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0006_auto_20180922_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='barcode',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='checkout_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registrations.CheckoutGroup'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='email_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registrations.EmailGroup'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registrations.Group'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='payment_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registrations.PaymentGroup'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='recnacc_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='state',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='participant',
            name='year_of_study',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
