# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-25 21:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regsoft', '0001_initial'),
        ('registrations', '0007_auto_20180922_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='regsoft.Bill'),
        ),
        migrations.AddField(
            model_name='participant',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='regsoft.Room'),
        ),
    ]
