# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-03 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0008_auto_20180926_0240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitsian',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
