# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-19 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0009_auto_20181004_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='is_chor',
            field=models.BooleanField(default=False),
        ),
    ]
