# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-27 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0011_participant_is_bus_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitsian',
            name='wants_refund',
            field=models.BooleanField(default=False),
        ),
    ]
