# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-26 12:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registrations', '0008_auto_20180926_0240'),
        ('events', '0004_auto_20180918_2110'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_the_event', models.BooleanField(default=False)),
                ('frozen', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.MainEvent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LevelClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='events.MainEvent')),
            ],
        ),
        migrations.CreateModel(
            name='LevelInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('levelclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='ems.LevelClass')),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ParameterClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('max_value', models.IntegerField(default=0)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='ems.LevelClass')),
            ],
        ),
        migrations.CreateModel(
            name='ParameterInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0)),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameterinstances', to='ems.Judge')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='ems.LevelInstance')),
                ('parameterclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='ems.ParameterClass')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='No Name', max_length=200)),
                ('score', models.IntegerField(default=0)),
                ('rank', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('P', 'Participant'), ('F', 'Finalist'), ('W', 'Winner')], default='P', max_length=1)),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.MainEvent')),
                ('leader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_leader', to='registrations.Participant')),
                ('leader_bitsian', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bitsian_leader', to='registrations.Bitsian')),
                ('members', models.ManyToManyField(to='registrations.Participant')),
                ('members_bitsian', models.ManyToManyField(to='registrations.Bitsian')),
            ],
        ),
    ]
