# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-27 03:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='judge',
            name='left_the_event',
        ),
        migrations.AddField(
            model_name='judge',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
