# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-20 04:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0003_clubdepartment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='levelinstance',
            name='participant',
        ),
        migrations.AddField(
            model_name='judge',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='levelinstance',
            name='position',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='levelinstance',
            name='score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='levelinstance',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='ems.Team'),
        ),
        migrations.AddField(
            model_name='parameterinstance',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='clubdepartment',
            name='coordinator',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='registrations.Bitsian'),
        ),
        migrations.AlterField(
            model_name='clubdepartment',
            name='events',
            field=models.ManyToManyField(blank=True, related_name='clubdept_event', to='events.MainEvent'),
        ),
        migrations.AlterField(
            model_name='clubdepartment',
            name='mobile',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='clubdepartment',
            name='profshows',
            field=models.ManyToManyField(blank=True, related_name='clubdept_prof_show', to='events.MainEvent'),
        ),
        migrations.AlterField(
            model_name='levelclass',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='parameterinstance',
            name='judge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_instances', to='ems.Judge'),
        ),
        migrations.AlterField(
            model_name='team',
            name='leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_leader', to='registrations.Participant'),
        ),
        migrations.AlterField(
            model_name='team',
            name='leader_bitsian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bitsian_leader', to='registrations.Bitsian'),
        ),
        migrations.AlterField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(blank=True, to='registrations.Participant'),
        ),
        migrations.AlterField(
            model_name='team',
            name='members_bitsian',
            field=models.ManyToManyField(blank=True, to='registrations.Bitsian'),
        ),
        migrations.AlterField(
            model_name='team',
            name='rank',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='score',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
